name: wt-santa
channels:
- conda-forge
dependencies:
- pip
- pyproj
- numpy
- pandas
- h5py
- netcdf4
- xarray
- scipy
- dask
- distributed
- pip:
  - git+https://github.com/deeplycloudy/xlma-python.git
